# Template to login into Dockerhub, build a docker image and push it.

# Parameters:
#
# - `dockerFilePath` is optional. If provided, will add the parameter: `-f ${{ parameters.dockerFile }}`
#   to the docker build command.
# - `folder` folder in which to build the Dockerfile
# - `imageName` is the built docker image name (not the tag)
# - `imageTag` is optional - if not provided the templateSetVariableDockerTag will be used to determine the tag.
# - `jobName` - should only include alphanumeric values and '_'.
# - `skip` - don't bother building if set to anything other than 'false'
# - `dockerBuildArgs` - extra arguments passed to docker build.
# - `extraJobs` can contain a list of jobs to do in the same stage which are dependent on the built and pushed docker image.

parameters:
  - name: 'dockerFilePath'
    default: ''
  - name: 'folder'
    default: ''
  - name: 'imageName'
    default: ''
  - name: 'imageTag'
    default: ''
  - name: 'jobName'
    default: ''
  - name: 'dockerBuildArgs'
    default: ''
  - name: 'extraJobs'
    type: object
    default: []
  - name: 'dependsOn'
    default: ''
  - name: 'skip'
    default: '$[false]'
  - name: 'skipf'
    default: false
  - name: 'skipt'
    default: true


jobs:
- job: skipcheckfalse
  pool:
    vmImage: "ubuntu-latest"
  condition: not('${{ parameters.skipf }}')
  dependsOn: ${{ parameters.dependsOn }}
  variables:
    SKIP: ${{ parameters.skipf }}
  steps:
    - bash: |
        echo "skip job variant 1"
        echo "Variable SKIP = \"$SKIP\""
        echo "Variable SKIP 2 = $(SKIP)"
        echo "condition true ?= ${{ not('${{ parameters.skipt }}') }}"
        echo "condition false ?= ${{ not('${{ parameters.skipf }}') }}"

- job: skipchecktrue
  pool:
    vmImage: "ubuntu-latest"
  condition: not('${{ parameters.skipt }}')
  dependsOn: ${{ parameters.dependsOn }}
  variables:
    SKIP: ${{ parameters.skipt }}
  steps:
    - bash: |
        echo "skip job variant 1"
        echo "Variable SKIP = \"$SKIP\""
        echo "Variable SKIP 2 = $(SKIP)"
        echo "condition true ?= ${{ not('${{ parameters.skipt }}') }}"
        echo "condition false ?= ${{ not('${{ parameters.skipf }}') }}"

- job: skipcheck3
  pool:
    vmImage: "ubuntu-latest"
  condition: eq(variables['SKIP'], False)
  dependsOn: ${{ parameters.dependsOn }}
  variables:
    SKIP: ${{ parameters.skip }}
  steps:
    - bash: |
        echo "skip job variant 1"
        echo "Variable SKIP = \"$SKIP\""
        echo "Variable SKIP 2 = $(SKIP)"
        echo "Variable SKIP eq False = ${{ eq(variables.SKIP, False) }}"
        echo "Variable SKIP eq false = ${{ eq(variables.SKIP, false) }}"
        echo "Variable SKIP eq true = ${{ eq(variables.SKIP, true) }}"
        echo "Not Variable SKIP = ${{ not(variables.SKIP) }}"

- job: skipcheck4
  pool:
    vmImage: "ubuntu-latest"
  condition: eq(variables['SKIP'], false)
  dependsOn: ${{ parameters.dependsOn }}
  variables:
    SKIP: ${{ parameters.skip }}
  steps:
    - bash: |
        echo "skip job variant 1"
        echo "Variable SKIP = \"$SKIP\""
        echo "Variable SKIP 2 = $(SKIP)"
        echo "Variable SKIP eq False = ${{ eq(variables.SKIP, False) }}"
        echo "Variable SKIP eq false = ${{ eq(variables.SKIP, false) }}"
        echo "Variable SKIP eq true = ${{ eq(variables.SKIP, true) }}"
        echo "Not Variable SKIP = ${{ not(variables.SKIP) }}"

- job: skipcheck5
  pool:
    vmImage: "ubuntu-latest"
  condition: not(eq(variables['SKIP'], 'True'))
  dependsOn: ${{ parameters.dependsOn }}
  variables:
    SKIP: ${{ parameters.skip }}
  steps:
    - bash: |
        echo "skip job variant 1"
        echo "Variable SKIP = \"$SKIP\""
        echo "Variable SKIP 2 = $(SKIP)"
        echo "Variable SKIP eq False = ${{ eq(variables.SKIP, False) }}"
        echo "Variable SKIP eq false = ${{ eq(variables.SKIP, false) }}"
        echo "Variable SKIP eq true = ${{ eq(variables.SKIP, true) }}"
        echo "Not Variable SKIP = ${{ not(variables.SKIP) }}"

- job: ${{ parameters.jobName }}
  displayName: ${{ parameters.jobName }}
  pool:
    vmImage: "ubuntu-latest"
  condition: ${{ eq(variables['SKIP'], 'False') }}
  dependsOn: ${{ parameters.dependsOn }}
  variables:
    DOCKER_TAG: ${{ parameters.imageTag }}
    SKIP: ${{ parameters.skip }}
    DOCKER_BUILD_ARGS: ${{ parameters.dockerBuildArgs }}
  steps:
    - bash: |
        if [ -z "$DOCKER_TAG" ]; then
          echo "Empty docker tag"
        else
          echo "Non empty docker tag $DOCKER_TAG"
        fi

        echo "Variable DOCKER_TAG = \"$DOCKER_TAG\""
        echo "Variable SKIP = \"$SKIP\""
        echo "Variable SKIP 2 = $(SKIP)"
        echo "Variable SKIP eq false = ${{ eq(variables.SKIP, false) }}"
        echo "Variable SKIP eq true = ${{ eq(variables.SKIP, true) }}"
        echo "Not Variable SKIP = ${{ not(variables.SKIP) }}"
        echo "Variable DOCKER_BUILD_ARGS = \"$DOCKER_BUILD_ARGS\""
      env:
        DOCKER_TAG: $(DOCKER_TAG)
      displayName: Echo tag parameter and variables
    - ${{ if eq(parameters.imageTag, '') }}:
      - template: templateSetVariableDockerTag.yml   # Set DOCKER_TAG if it wasn't provided in parameters as imageTag
    - script: |
        docker login -u $(dockerHubId) -p $(dockerHubPassword)
      displayName: 'Dockerhub login'
    - script: |
        if [[ -z "${{ parameters.dockerFilePath }}" ]]; then
          docker build -t ${{ parameters.imageName }}:$(DOCKER_TAG) $(DOCKER_BUILD_ARGS) ${{ parameters.folder }}
        else
          docker build -t ${{ parameters.imageName }}:$(DOCKER_TAG) -f ${{ parameters.dockerFilePath }} $(DOCKER_BUILD_ARGS) ${{ parameters.folder }}
        fi
        docker push ${{ parameters.imageName }}:$(DOCKER_TAG)
      displayName: 'Build and push docker image'

# Updated from the documentation https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops
# The idea being able to define jobs depending on the creation of the previous image.
- ${{ each job in parameters.jobs }}: # Then do each job
  - ${{ each pair in job }}:          # Insert all properties other than "dependsOn"
      ${{ if ne(pair.key, 'dependsOn') }}:
        ${{ pair.key }}: ${{ pair.value }}
    dependsOn:                        # Inject dependency
    - ${{ parameters.jobName }}
    - ${{ if job.dependsOn }}:
      - ${{ job.dependsOn }}
